### ISSUE TITLE
vue-meteor app doesn’t load

### ISSUE THREAD

**Issue by GeoffreyBooth** [meteor-vue/vue-meteor#194]
Picking up from #182, the Meteor app in the `vue-meteor` repo itself doesn’t start. This makes me nervous about the stability of these packages, to put it mildly. A [comment](https://github.com/Akryum/vue-meteor/issues/182#issuecomment-304439974) from @Akryum when I brought this up on that thread said to use the `vue-meteor-demo` project instead, but that project only uses the `akryum:vue-component`, `akryum:vue-less` and `akryum:vue-ssr` packages; unlike `vue-meteor`, which additionally uses `akryum:vue`, `akryum:vue-router`, `akryum:vuex`, `akryum:vue-i18n`, `akryum:vue-i18n-ui`, `akryum:vue-sass`, `akryum:vue-jade` and `akryum:vue-coffee` packages. I think there should be a demo that tests all the packages together, to prove that they all work and showing what versions are known to work together.

Here’s an abbreviated version of checking out this repo and starting it up:
```
 ✦ git clone git@github.com:Akryum/vue-meteor.git
Cloning into 'vue-meteor'...
remote: Counting objects: 3008, done.
remote: Compressing objects: 100% (31/31), done.
remote: Total 3008 (delta 19), reused 29 (delta 13), pack-reused 2964
Receiving objects: 100% (3008/3008), 740.47 KiB | 0 bytes/s, done.
Resolving deltas: 100% (2033/2033), done.
Checking connectivity... done.
 ✦ cd vue-meteor
 ✦ meteor npm install
npm WARN deprecated @types/promises-a-plus@0.0.26: Use '--lib es6' to get Promise types.
npm WARN deprecated @types/redux@3.6.0: This is a stub types definition for Redux (https://github.com/reactjs/redux). Redux provides its own type definitions, so you don't need @types/redux installed!
meteor-vue-component@ /private/tmp/vue-meteor
├─┬ apollo-client@0.5.26
# ...
└── vuex@1.0.1

 ✦ meteor
[[[[[ /private/tmp/vue-meteor ]]]]]

=> Started proxy.
=> Meteor 1.5 is available. Update this project with 'meteor update'.
=> Started MongoDB.
akryum:vue: updating npm dependencies -- lodash.omit...
vue-component-coffee: updating npm dependencies -- coffeescript, source-map...
akryum:vue-component-dev-client: updating npm dependencies -- socket.io-client...
vue-component: updating npm dependencies -- postcss, postcss-selector-parser, postcss-modules, socket.io, async, lodash, hash-sum, source-map, source-map-merger, generate-source-map, autoprefixer,
vue-template-compiler, vue-template-es2015-compiler, parse5, colors...
   [HMR] Dev server listening on port 3003
vue-i18n: updating npm dependencies -- lodash...
vue-component-less: updating npm dependencies -- less...
vue-component-jade: updating npm dependencies -- jade...
vue-component-sass: updating npm dependencies -- node-sass, meteor-project-path...
vue-component-stylus: updating npm dependencies -- stylus, nib...
akryum:vuex: updating npm dependencies -- lodash...

Changes to your project's package version selections:

akryum:vue-compiler              removed from your project
akryum:vue-component             upgraded from 0.8.7 to 0.9.2
akryum:vue-component-dev-client  upgraded from 0.2.5 to 0.2.12
akryum:vue-component-dev-server  upgraded from 0.0.5 to 0.0.9
akryum:vue-jade                  upgraded from 0.0.1 to 0.0.2
akryum:vue-less                  upgraded from 0.0.4 to 0.0.5
akryum:vue-sass                  upgraded from 0.0.4 to 0.0.7
akryum:vue-stylus                upgraded from 0.0.4 to 0.0.5
spacebars-compiler               upgraded from 1.1.0 to 1.1.2
templating-tools                 upgraded from 1.1.0 to 1.1.2

WARNING: npm peer requirements (for apollo) not installed:
 - graphql-server-express@0.4.4 installed, graphql-server-express@^0.5.0 needed
 - graphql-tools@0.8.4 installed, graphql-tools@^0.9.0 needed

Read more about installing npm peer dependencies:
  http://guide.meteor.com/using-packages.html#peer-npm-dependencies

Warning - the `printer` exports from `graphql-tag` will be removed in the next major version.
See https://github.com/apollographql/graphql-tag/issues/54 for more information.
/Users/Geoffrey/.meteor/packages/meteor-tool/.1.4.3_1.1h1l0lv++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
						throw(ex);
						^

TypeError: StoreSubModule is not a function
    at meteorInstall.imports.vuex.modules.forum.js (imports/vuex/modules/forum.js:3:19)
    at fileEvaluate (packages/modules-runtime.js:197:9)
    at Module.require (packages/modules-runtime.js:120:16)
    at Module.Mp.import (/Users/Geoffrey/.meteor/packages/modules/.0.7.9.1h4id3m++os+web.browser+web.cordova/npm/node_modules/reify/lib/runtime.js:75:16)
    at meteorInstall.imports.vuex.store.js (imports/vuex/store.js:1:156)
    at fileEvaluate (packages/modules-runtime.js:197:9)
    at Module.require (packages/modules-runtime.js:120:16)
    at Module.Mp.import (/Users/Geoffrey/.meteor/packages/modules/.0.7.9.1h4id3m++os+web.browser+web.cordova/npm/node_modules/reify/lib/runtime.js:75:16)
    at imports/ui/vuex/Tracker.vue:23:1
    at meteorInstall.imports.ui.vuex.VuexDemo.vue (imports/ui/vuex/VuexDemo.vue:12:1)
=> Exited with code: 1
# …
=> Your application is crashing. Waiting for file change.
```

**Comment by Akryum** [comment]
Just a quick note: `akryum:vuex`, `akryum:vue-i18n`, `akryum:vue-i18n-ui` are not currently compatible with Vue 2, and the testing code present in the vue-meteor repository is Vue 1.

**Comment by Akryum** [comment]
The demo project for Meteor 1.5 and Vue 2.x is [vue-meteor-demo](https://github.com/meteor-vue/vue-meteor-demo). If you feel it miss something, please contribute! :smile:
