### ISSUE TITLE
vue-stylus: error during style.render() "Path must be a string. Received undefined"

### ISSUE THREAD

**Issue by brewingcode** [meteor-vue/vue-meteor#198]
When attempting to use stylus in the `<script lang="stylus">` block of a .vue component, I get an error "Path must be a string. Received undefined". 

I've googled a bit around it, but only found lots of chaff about Node v6 breaking the world. However, I get this error regardless of the Node version I use: v4, v5, v6, v7 all do the same thing. It's possible I'm not testing that properly: I'm using `nvm` to swap versions and re-starting `meteor` each time, but for all I know Meteor is running a cached binary or something.

To repro:

```
git clone https://github.com/Akryum/meteor-vue2-example
cd meteor-vue2-example
meteor add akryum:vue-stylus
```

...and then replace the `<style>` of a .vue component, for example `imports/ui/App.vue`:

```
<style lang="stylus">
body
  background-color: green
</style>
```

...and run `meteor`. I see the following error:

```
[21:31:58] $ meteor
[[[[[ /private/tmp/meteor-vue2-example ]]]]]

=> Started proxy.
=> Meteor 1.5 is available. Update this project with 'meteor update'.
=> Started MongoDB.
   [HMR] Dev server listening on port 3003
[vue-component] Error while compiling in tag <style> using lang stylus -> in imports/ui/App.vue at line 69
[TypeError: undefined:3:1
   1| body
   2|   background-color: green
   3|
------^

Path must be a string. Received undefined
]
// snip
=> Your application has errors. Waiting for file change.
```

I setup a local working copy of `vue-stylus` (at least I think I did, I symlinked `meteor-vue2-example/packages/vue-stylus` to a directory with my own copy of this package), and was doing some printf debugging, which led to the error handling of [`style.render()`](https://github.com/Akryum/vue-meteor/blob/master/packages/vue-stylus/vue-stylus.js#L83). I added an extra `console.log` with a stack trace plus some other variables:

```
 let style = stylus(source)
    .use(nib())
    .set('filename', basePath)
    .set('sourcemap', { inline: false, comment: false })
    .set('cache', true)
    .set('importer', importer);

  style.render((err, css) => {
    if (err) {
      console.log('style.render error: ', source, basePath, inputFile, err.stack);
      cb(err, null);
```

....which produces:

```
[[[[[ /private/tmp/meteor-vue2-example ]]]]]

=> Started proxy.
=> Meteor 1.5 is available. Update this project with 'meteor update'.
   [HMR] Dev server listening on port 3003
style.render error:  bodyer                  |
  background-color: green
 undefined InputFile {
  _resourceSlot:
   ResourceSlot {
     inputResource:
      { type: 'source',
        extension: 'vue',
        usesDefaultSourceProcessor: false,
        data: <Buffer 3c 74 65 6d 70 6c 61 74 65 3e 0a 3c 64 69 76 20 63 6c 61 73 73 3d 22 61 70 70 22 3e 0a 20 20 3c 68 31 3e 53 69 6d 70 6c 65 20 4d 65 74 65 6f 72 20 65 ... >,
        path: 'imports/ui/App.vue',
        hash: 'a79b71bce8e26b69c335717113789716d09c0727',
        fileOptions: [Object] },
     outputResources: [],
     jsOutputResources: [],
     sourceProcessor:
      { isopack: [Object],
        extensions: [Object],
        filenames: [Object],
        archMatching: 'web',
        isTemplate: false,
        factoryFunction: [Function],
        methodName: 'registerCompiler',
        id: 'akryum:vue-component#6',
        userPlugin: [Object] },
     packageSourceBatch:
      PackageSourceBatch {
        unibuild: [Object],
        processor: [Object],
        sourceRoot: '/private/tmp/meteor-vue2-example',
        linkerCacheDir: '/private/tmp/meteor-vue2-example/.meteor/local/bundler-cache/linker',
        importExtensions: [Object],
        _resolver: null,
        resourceSlots: [Object],
        importedSymbolToPackageName: [Object],
        useMeteorInstall: true } },
  _statCache: {},
  _controlFileCache: {},
  _resolveCache: {} } TypeError: undefined:3:1
   1| body
   2|   background-color: green
   3|
------^

Path must be a string. Received undefined

    at assertPath (path.js:8:11)
    at posix.relative (path.js:496:3)
    at SourceMapper.normalizePath (/private/tmp/meteor-vue2-example/.meteor/local/isopacks/akryum_vue-stylus/plugin.vue-component-stylus.os/npm/node_modules/meteor/vue-component-stylus/node_modules/stylus/lib/visitor/sourcemapper.js:146:10)
    at SourceMapper.out (/private/tmp/meteor-vue2-example/.meteor/local/isopacks/akryum_vue-stylus/plugin.vue-component-stylus.os/npm/node_modules/meteor/vue-component-stylus/node_modules/stylus/lib/visitor/sourcemapper.js:96:25)
    at SourceMapper.Compiler.visitGroup (/private/tmp/meteor-vue2-example/.meteor/local/isopacks/akryum_vue-stylus/plugin.vue-component-stylus.os/npm/node_modules/meteor/vue-component-stylus/node_modules/stylus/lib/visitor/compiler.js:440:26)
    at SourceMapper.Visitor.visit (/private/tmp/meteor-vue2-example/.meteor/local/isopacks/akryum_vue-stylus/plugin.vue-component-stylus.os/npm/node_modules/meteor/vue-component-stylus/node_modules/stylus/lib/visitor/index.js:28:40)
    at SourceMapper.Compiler.visitRoot (/private/tmp/meteor-vue2-example/.meteor/local/isopacks/akryum_vue-stylus/plugin.vue-component-stylus.os/npm/node_modules/meteor/vue-component-stylus/node_modules/stylus/lib/visitor/compiler.js:104:20)
    at SourceMapper.Visitor.visit (/private/tmp/meteor-vue2-example/.meteor/local/isopacks/akryum_vue-stylus/plugin.vue-component-stylus.os/npm/node_modules/meteor/vue-component-stylus/node_modules/stylus/lib/visitor/index.js:28:40)
    at SourceMapper.Compiler.compile (/private/tmp/meteor-vue2-example/.meteor/local/isopacks/akryum_vue-stylus/plugin.vue-component-stylus.os/npm/node_modules/meteor/vue-component-stylus/node_modules/stylus/lib/visitor/compiler.js:53:15)
    at SourceMapper.compile (/private/tmp/meteor-vue2-example/.meteor/local/isopacks/akryum_vue-stylus/plugin.vue-component-stylus.os/npm/node_modules/meteor/vue-component-stylus/node_modules/stylus/lib/visitor/sourcemapper.js:69:21)
    at Renderer.render (/private/tmp/meteor-vue2-example/.meteor/local/isopacks/akryum_vue-stylus/plugin.vue-component-stylus.os/npm/node_modules/meteor/vue-component-stylus/node_modules/stylus/lib/renderer.js:96:24)
    at packages/vue-component-stylus/vue-stylus.js:81:9
    at packages/meteor.js:212:23
// snip: 67 more stack entries, not even joking
[vue-component] Error while compiling in tag <style> using lang stylus -> in imports/ui/App.vue at line 69
[TypeError: undefined:3:1
   1| body
   2|   background-color: green
   3|
------^

Path must be a string. Received undefined
]
```

**Comment by brewingcode** [comment]
I have a workaround for now, but it's such a god-awful hack that I don't want to PR it.

```
diff --git a/packages/vue-stylus/vue-stylus.js b/packages/vue-stylus/vue-stylus.js
index b092d33..34f753c 100644
--- a/packages/vue-stylus/vue-stylus.js
+++ b/packages/vue-stylus/vue-stylus.js
@@ -73,7 +73,7 @@ global.vue.lang.stylus = Meteor.wrapAsync(function({
 
   let style = stylus(source)
     .use(nib())
-    .set('filename', basePath)
+    .set('filename', '/dev/null')
     .set('sourcemap', { inline: false, comment: false })
     .set('cache', true)
     .set('importer', importer);
-- 
```

**Comment by Akryum** [comment]
So the issue is `basePath` being undefined?

**Comment by brewingcode** [comment]
Maybe...? `basePath` is used elsewhere without any noticeable issue. `basePath` is passed in by.....Vue? I have no idea how Vue loads these plugins to handle its `<template|script|style>` blocks.

**Comment by Akryum** [comment]
Do you have a reproduction repo?

**Comment by brewingcode** [comment]
Repro is in the original post, here it is with a curl command for complete copy-pasteability:

```
git clone https://github.com/Akryum/meteor-vue2-example
cd meteor-vue2-example
meteor add akryum:vue-stylus
curl -o imports/ui/App.vue https://gist.githubusercontent.com/brewingcode/c0d9a266f92ddd842f0221387d762e89/raw/338d80342bb8eddcdbb4d726077c14dd8b8628a8/App.vue
meteor
```

**Comment by brewingcode** [comment]
Haha, wow nevermind my last comment, my brain _completely_ dropped the word "repo", which turns out is rather important.

```
git clone https://github.com/brewingcode/meteor-vue2-example -b issue-198
```

**Comment by MartinBucko** [comment]
+1  `METEOR@1.6-beta.4`

```
accounts-base            1.4.0-beta.4  A user account system
accounts-password        1.5.0-beta.4* Password support for accounts
akryum:vue               1.2.2  Integrate Vue with Meteor
akryum:vue-coffee        0.0.5  Add coffee support for vue components
akryum:vue-component     0.10.0  VueJS single-file components that hot-reloads
akryum:vue-pug           0.0.2  Add pug support for vue components
akryum:vue-router2       0.1.0  Easy vue routing for Meteor - vue-router 2.x
akryum:vue-stylus        0.0.5  Add stylus support for vue components
alanning:roles           1.2.16  Authorization package for Meteor
aldeed:collection2       2.10.0  Automatic validation of insert and update operations on the client and server.
aldeed:simple-schema     1.5.3  A simple schema validation object with reactivity. Used by collection2 and autoform.
coffeescript             1.12.6_1  Javascript dialect with fewer braces and semicolons
ecmascript               0.9.0-beta.4  Compiler plugin that supports ES2015+ in all .js files
es5-shim                 4.6.15  Shims and polyfills to improve ECMAScript 5 support
http                     1.3.0-beta.4  Make HTTP calls to remote servers
matb33:collection-hooks  0.8.4  Extends Mongo.Collection with before/after hooks for insert/update/remove/find/findOne
meteor-base              1.2.0-beta.4* Packages that every Meteor app needs
mobile-experience        1.0.4  Packages for a great mobile user experience
mongo                    1.2.0-beta.4* Adaptor for using MongoDB and Minimongo over DDP
netanelgilad:excel       0.2.6  Parse excel worksheets for your meteor app.
percolate:migrations     1.0.2  Define and run db migrations.
shell-server             0.3.0-beta.4  Server-side component of the `meteor shell` command.
standard-minifier-css    1.3.4  Standard css minifier used with Meteor apps by default.
standard-minifier-js     2.2.0-beta.4* Standard javascript minifiers used with Meteor apps by default.
static-html              1.2.2  Define static page content in .html files
stylus                   2.513.10-beta.4  Expressive, dynamic, robust CSS
tmeasday:publish-counts  0.8.0  Publish the count of a cursor, in real time
tracker                  1.1.3  Dependency tracker to allow reactive callbacks
vsivsi:file-collection   1.3.8  Collections that efficiently store files using MongoDB GridFS, with built-in HTTP support
```

Log:

```
=> Started proxy.                             
   [HMR] Dev server listening on port 3003
=> Errors prevented startup:                  
   
   While building for web.browser:
   imports/users/ui/Login.vue:122: [vue-component] Error while compiling in tag <style> using lang stylus /home/martinez/www/ids-mrp/web/imports/users/ui/Login.vue:3:12
   1| 
   2| .md-subheader
   3|     padding: 0
   -----------------^
   
   Path must be a string. Received undefined
   
   imports/components/tables/TableFilter.vue:178: [vue-component] Error while compiling in tag <style> using lang stylus /home/martinez/www/ids-mrp/web/imports/components/tables/TableFilter.vue:5:1
   1| 
   2| 
   3| .filter
   4|     margin: 0 8px
   5| 
   ------^
   
   Path must be a string. Received undefined
   
   imports/app/ui/AppLayout.vue:156: [vue-component] Error while compiling in tag <style> using lang stylus /home/martinez/www/ids-mrp/web/imports/app/ui/AppLayout.vue:5:1
   1| 
   2| 
   3| .tabs-main
   4|     flex: 1
   5| 
   ------^
   
   Path must be a string. Received undefined
   
   imports/components/forms/FieldInput.vue:517: [vue-component] Error while compiling in tag <style> using lang stylus /home/martinez/www/ids-mrp/web/imports/components/forms/FieldInput.vue:19:21
   15| 
   16| .label
   17|     font-size 12px
   18|     color: rgba(0,0,0,.54)
   19|     line-heeight: 20px;
   ---------------------------^
   
   Path must be a string. Received undefined
   
   imports/components/forms/FieldFile.vue:201: [vue-component] Error while compiling in tag <style> using lang stylus /home/martinez/www/ids-mrp/web/imports/components/forms/FieldFile.vue:7:18
   3|     padding: 6px
   4| .file-img img
   5|     max-width: 300px
   6| .del-btn
   7|     padding-top: 8px
   -----------------------^
   
   Path must be a string. Received undefined
   
   imports/components/forms/FieldInputArray.vue:77: [vue-component] Error while compiling in tag <style> using lang stylus /home/martinez/www/ids-mrp/web/imports/components/forms/FieldInputArray.vue:5:1
   1| 
   2| 
   3| .field-input-array
   4|     width: 100%
   5| 
   ------^
   
   Path must be a string. Received undefined
   
   
=> Your application has errors. Waiting for file change.
=> Started MongoDB.                           
```

**Comment by MartinBucko** [comment]
@Akryum 
Updating stylus to never version fix this error in: 
https://github.com/meteor-vue/vue-meteor/blob/master/packages/vue-stylus/package.js#L18 

to:
stylus: 'https://github.com/meteor/stylus/tarball/bb47a357d132ca843718c63998eb37b90013a449', // fork of 0.54.5
