### ISSUE TITLE
Vue-component hot reload not working for css files

### ISSUE THREAD

**Issue by SnooHD** [meteor-vue/vue-meteor#232]
I have an issue with the hot reload when i change any of my scss files.
I dont have any problems with other files types.

Error server side:
`Exception in callback of async function: TypeError: Cannot read property 'hash' of null
    at hotCompile (packages/vue-component/plugin/vue-compiler.js:324:15)
    at runWithEnvironment (packages/meteor.js:1176:24)`

Error client side:
`[vue-component] Error while compiling in tag <style> using lang scss File to import not found or unreadable: C:\Users\Mike\Meteor\logopicker\imports\client\ui\step3\tools\tools.scss.
Parent style sheet: stdin`

If any other details are needed, let me know.
Thanks a bunch!

**Comment by alexandesigner** [comment]
In your `.vue` file you set `lang="scss"` ?

`<style lang="scss"></style>`

**Comment by SnooHD** [comment]
This is my style tag:
`
<style lang="scss">
  @import 'tools';
</style>
`
Funny thing is that sometimes it does seem to work as it should..

**Comment by alexandesigner** [comment]
Checks the path of the file you are importing.

I've created a play and it seems to be working fine, take a look and see what may be different:

See https://github.com/alexandesigner/meteor-vue-issue232

For more information visit [Package SASS](https://github.com/meteor-vue/vue-meteor/tree/master/packages/vue-sass)

**Comment by SnooHD** [comment]
Hmm i guess i should mention that i'm changing the files from a different computer on my local network.
When i directly change the files on the computer running meteor, its seems to work fine.
When i use my laptop to change the files through the network using file sharing, i get this error..

FYI;
I don't have a second screen to attach to my computer so i'm using my laptop for this purpose.

**Comment by Akryum** [comment]
This may be a nodejs limitation. I didn't try editing the project file over the network yet.
