### ISSUE TITLE
Making akryum:vue-ssr working with Vue Head

### ISSUE THREAD

**Issue by nizulzaim** [meteor-vue/vue-meteor#249]
Hi Akryum,

When i install vue head in project which is using your vue-ssr, it will print out this error:

```
ReferenceError: window is not defined
W20170908-01:06:50.238(8)? (STDERR)     at /mnt/d/project/bongkah/node_modules/vue-head/vue-head.js:7:17
W20170908-01:06:50.238(8)? (STDERR)     at Object.<anonymous> (/mnt/d/project/bongkah/node_modules/vue-head/vue-head.js:262:3
)
W20170908-01:06:50.239(8)? (STDERR)     at Module._compile (module.js:573:30)
W20170908-01:06:50.239(8)? (STDERR)     at Object.Module._extensions..js (module.js:584:10)
W20170908-01:06:50.240(8)? (STDERR)     at Module.load (module.js:507:32)
W20170908-01:06:50.240(8)? (STDERR)     at tryModuleLoad (module.js:470:12)
W20170908-01:06:50.240(8)? (STDERR)     at Function.Module._load (module.js:462:3)
W20170908-01:06:50.241(8)? (STDERR)     at Module.require (module.js:517:17)
W20170908-01:06:50.241(8)? (STDERR)     at require (internal/module.js:11:18)
W20170908-01:06:50.241(8)? (STDERR)     at npmRequire (/mnt/d/project/bongkah/.meteor/local/build/programs/server/npm-require
.js:133:10)
```

I know the fact is **window** is not defined in server/node which is why it will give this error in console. I get one workaround thanks to dynamic importing in meteor:

```js
if (Meteor.isClient) {
    import VueHead from 'vue-head'
    Vue.use(VueHead)
}
```

However, this workaround I think will definitely making SEO friendly website useless because of VueHead will only imported when using client side rendering only. I hope you can give recommendation or fix on this issue?

**Comment by Akryum** [comment]
It seems the package is not compatible with SSR. You can open an issue or contribute to it to get this fixed.

**Comment by nizulzaim** [comment]
Ok. thank you
