### ISSUE TITLE
Vue packages version mismatch:

### ISSUE THREAD

**Issue by SethaVa** [meteor-vue/vue-meteor#284]
Get error
```js
While loading plugin `vue-component` from package `akryum:vue-component`:

   /home/dara/.meteor/packages/akryum_vue-component/.0.10.8.1xwfgla.etjo++os+web.browser+web.cordova/plugin.vue-component.os/npm/node_modules/meteor/vue-component/node_modules/vue-template-compiler/index.js:8:9: 
   
   Vue packages version mismatch:
   
   - vue@1.0.26
   - vue-template-compiler@2.4.4
   
   This may cause things to work incorrectly. Make sure to use the same version for both.
   If you are using vue-loader@>=10.0, simply update vue-template-compiler.
   If you are using vue-loader@<10.0 or vueify, re-installing vue-loader/vueify should bump vue-template-compiler to the latest.
   
   at Object.<anonymous>
   (/home/dara/.meteor/packages/akryum_vue-component/.0.10.8.1xwfgla.etjo++os+web.browser+web.cordova/plugin.vue-component.os/npm/node_modules/meteor/vue-component/node_modules/vue-template-compiler/index.js:8:9)
   at Module._compile (module.js:635:30)
   at Object.Module._extensions..js (module.js:646:10)
   at Module.load (module.js:554:32)
   at Module.Mp.load (/tools/tool-env/install-runtime.js:16:29)
   at tryModuleLoad (module.js:497:12)
   at Function.Module._load (module.js:489:3)
   at Module.require (module.js:579:17)
   at require (internal/module.js:11:18)
   at npmRequire (/tools/isobuild/bundler.js:1993:14)
   at Module.useNode (packages/modules-runtime.js:687:18)
   at fileEvaluate (packages/modules-runtime.js:332:20)
   at require (packages/modules-runtime.js:228:16)
   at vue-compiler.js (packages/vue-component/plugin/vue-compiler.js:13:22)
   at fileEvaluate (packages/modules-runtime.js:333:9)
   at require (packages/modules-runtime.js:228:16)
   at <runJavaScript-19>:26169:1
   at <runJavaScript-19>:26176:3
   
   
=> Your application has errors. Waiting for file change.
=> Started MongoDB.                           
```
My Package
```js
// NPM
{
  "name": "meteorEx",
  "private": true,
  "scripts": {
    "start": "meteor run"
  },
  "dependencies": {
    "babel-runtime": "^6.26.0",
    "meteor-node-stubs": "^0.3.2",
    "vue": "^2.5.8"
  }
}
---------------------
// Meteor
# Meteor packages used by this project, one per line.
# Check this file (and the other files in this directory) into your repository.
#
# 'meteor add' and 'meteor remove' will edit this file for you,
# but you can also edit it by hand.

meteor-base@1.2.0             # Packages every Meteor app needs to have
mobile-experience@1.0.5       # Packages for a great mobile UX
mongo@1.3.1                   # The database Meteor supports right now
#blaze-html-templates@1.0.4 # Compile .html files into Meteor Blaze views
reactive-var@1.0.11            # Reactive variable for tracker
tracker@1.1.3                 # Meteor's client-side reactive programming library

standard-minifier-css@1.3.5   # CSS minifier run for production mode
standard-minifier-js@2.2.0    # JS minifier run for production mode
es5-shim@4.6.15                # ECMAScript 5 compatibility for older browsers
ecmascript@0.9.0              # Enable ECMAScript2015+ syntax in app code
shell-server@0.3.0            # Server-side component of the `meteor shell` command

autopublish@1.0.7             # Publish all data to the clients (for prototyping)
insecure@1.0.7                # Allow all DB writes from clients (for prototyping)

static-html
dynamic-import

fortawesome:fontawesome
akryum:vue-component@=0.10.8
```

**Comment by tarvos21** [comment]
Hi, I got exactly the same error, when running `meteor update` or `meteor run` or `meteor`.

@SethaVa, how do you finally make the project running properly?
