### ISSUE TITLE
Illegal HTML attribute name: @click

### ISSUE THREAD

**Issue by mathus13** [meteor-vue/vue-meteor#303]
Running `meteor`
I get the error 
```
Errors prevented bundling:                    
While processing files with templating-compiler (for target web.browser):
packages/htmljs.js:623:15: Illegal HTML attribute name: @click
```
I have tried converting all instance of the shorthand `@click` to `v-on:click`, but still get the same error. Must be in a dependency, but `@click` should not be an issue.

What is missing?

__packages__
- matb33:bootstrap-glyphicons
- gwendall:auth-client-callbacks
- akryum:vue-component
- session@1.1.7
- akryum:vue-sass
- akryum:vue-blaze-template
- aldeed:collection2-core@2.0.0

__package.json__
```
"dependencies": {
    "axios": "^0.17.1",
    "bcrypt": "^1.0.3",
    "bootstrap": "^3.3.7",
    "bootstrap-sass": "^3.3.7",
    "buffer": "^5.0.8",
    "lodash": "^4.17.5",
    "moment": "^2.20.1",
    "pubsub-js": "^1.6.0",
    "simpl-schema": "^1.4.2",
    "vue": "^2.5.13",
    "vue-form-generator": "^2.2.0",
    "vue-meteor-tracker": "^1.2.0",
    "vue-router": "^2.3.0",
    "vue-select": "^2.4.0",
    "vue2-google-maps": "^0.8.4",
    "vuelidate": "^0.6.1",
    "vuex": "^3.0.1"
  }
```

__Full Trace__
```
Errors prevented bundling:                    
While processing files with templating-compiler (for target web.browser):
packages/htmljs.js:623:15: Illegal HTML attribute name: @click
at Object.HTML.flattenAttributes (packages/htmljs.js:623:15)
at HTMLVisitorSubtype.visitTag (packages/htmljs.js:323:20)
at HTMLVisitorSubtype.visit (packages/htmljs.js:88:32)
at Object.HTML.toHTML (packages/htmljs.js:638:35)
at toRaw (packages/spacebars-compiler.js:657:24)
at HTMLVisitorSubtype.visitTag (packages/spacebars-compiler.js:693:14)
at HTMLVisitorSubtype.visit (packages/htmljs.js:88:32)
at HTMLVisitorSubtype.visitArray (packages/htmljs.js:142:32)
at HTMLVisitorSubtype.visitChildren (packages/spacebars-compiler.js:702:49)
at HTMLVisitorSubtype.visitTag (packages/htmljs.js:161:42)
at HTMLVisitorSubtype.visitTag (packages/spacebars-compiler.js:695:49)
at HTMLVisitorSubtype.visit (packages/htmljs.js:88:32)
at HTMLVisitorSubtype.visitArray (packages/htmljs.js:142:32)
at HTMLVisitorSubtype.visitChildren (packages/spacebars-compiler.js:702:49)
at HTMLVisitorSubtype.visitTag (packages/htmljs.js:161:42)
at HTMLVisitorSubtype.visitTag (packages/spacebars-compiler.js:695:49)
at HTMLVisitorSubtype.visit (packages/htmljs.js:88:32)
at HTMLVisitorSubtype.visitArray (packages/htmljs.js:142:32)
at HTMLVisitorSubtype.visitArray (packages/spacebars-compiler.js:685:51)
at HTMLVisitorSubtype.visit (packages/htmljs.js:101:32)
at Object.SpacebarsCompiler.optimize (packages/spacebars-compiler.js:750:34)
at Object.SpacebarsCompiler.codeGen (packages/spacebars-compiler.js:1318:30)
at Object.SpacebarsCompiler.compile (packages/spacebars-compiler.js:1258:28)
at SpacebarsTagCompiler.addTagToResults (packages/templating-tools/compile-tags-with-spacebars.js:65:50)
at packages/templating-tools/compile-tags-with-spacebars.js:5:13
at Array.forEach (<anonymous>)
at CachingHtmlCompiler.compileTagsWithSpacebars (packages/templating-tools/compile-tags-with-spacebars.js:4:8)
at CachingHtmlCompiler.compileOneFile (packages/caching-html-compiler/caching-html-compiler.js:61:19)
at packages/caching-compiler/caching-compiler.js:299:32
at
/home/sbarratt/.meteor/packages/templating-compiler/.1.3.3.19xoaaa.rbiig++os+web.browser+web.cordova/plugin.compileTemplatesBatch.os/npm/node_modules/meteor/caching-compiler/node_modules/async/lib/async.js:182:20
at replenish
(/home/sbarratt/.meteor/packages/templating-compiler/.1.3.3.19xoaaa.rbiig++os+web.browser+web.cordova/plugin.compileTemplatesBatch.os/npm/node_modules/meteor/caching-compiler/node_modules/async/lib/async.js:317:21)
at
/home/sbarratt/.meteor/packages/templating-compiler/.1.3.3.19xoaaa.rbiig++os+web.browser+web.cordova/plugin.compileTemplatesBatch.os/npm/node_modules/meteor/caching-compiler/node_modules/async/lib/async.js:324:29
at
/home/sbarratt/.meteor/packages/templating-compiler/.1.3.3.19xoaaa.rbiig++os+web.browser+web.cordova/plugin.compileTemplatesBatch.os/npm/node_modules/meteor/caching-compiler/node_modules/async/lib/async.js:44:16
at packages/caching-compiler/caching-compiler.js:316:9
at
/home/sbarratt/.meteor/packages/templating-compiler/.1.3.3.19xoaaa.rbiig++os+web.browser+web.cordova/plugin.compileTemplatesBatch.os/npm/node_modules/meteor/caching-compiler/node_modules/async/lib/async.js:182:20
at replenish
(/home/sbarratt/.meteor/packages/templating-compiler/.1.3.3.19xoaaa.rbiig++os+web.browser+web.cordova/plugin.compileTemplatesBatch.os/npm/node_modules/meteor/caching-compiler/node_modules/async/lib/async.js:317:21)
at
/home/sbarratt/.meteor/packages/templating-compiler/.1.3.3.19xoaaa.rbiig++os+web.browser+web.cordova/plugin.compileTemplatesBatch.os/npm/node_modules/meteor/caching-compiler/node_modules/async/lib/async.js:324:29
at
/home/sbarratt/.meteor/packages/templating-compiler/.1.3.3.19xoaaa.rbiig++os+web.browser+web.cordova/plugin.compileTemplatesBatch.os/npm/node_modules/meteor/caching-compiler/node_modules/async/lib/async.js:44:16
at packages/caching-compiler/caching-compiler.js:316:9
at
/home/sbarratt/.meteor/packages/templating-compiler/.1.3.3.19xoaaa.rbiig++os+web.browser+web.cordova/plugin.compileTemplatesBatch.os/npm/node_modules/meteor/caching-compiler/node_modules/async/lib/async.js:182:20
at replenish
(/home/sbarratt/.meteor/packages/templating-compiler/.1.3.3.19xoaaa.rbiig++os+web.browser+web.cordova/plugin.compileTemplatesBatch.os/npm/node_modules/meteor/caching-compiler/node_modules/async/lib/async.js:317:21)
at
/home/sbarratt/.meteor/packages/templating-compiler/.1.3.3.19xoaaa.rbiig++os+web.browser+web.cordova/plugin.compileTemplatesBatch.os/npm/node_modules/meteor/caching-compiler/node_modules/async/lib/async.js:324:29
at
/home/sbarratt/.meteor/packages/templating-compiler/.1.3.3.19xoaaa.rbiig++os+web.browser+web.cordova/plugin.compileTemplatesBatch.os/npm/node_modules/meteor/caching-compiler/node_modules/async/lib/async.js:44:16
at packages/caching-compiler/caching-compiler.js:316:9
at
/home/sbarratt/.meteor/packages/templating-compiler/.1.3.3.19xoaaa.rbiig++os+web.browser+web.cordova/plugin.compileTemplatesBatch.os/npm/node_modules/meteor/caching-compiler/node_modules/async/lib/async.js:182:20
at replenish
(/home/sbarratt/.meteor/packages/templating-compiler/.1.3.3.19xoaaa.rbiig++os+web.browser+web.cordova/plugin.compileTemplatesBatch.os/npm/node_modules/meteor/caching-compiler/node_modules/async/lib/async.js:317:21)
at
/home/sbarratt/.meteor/packages/templating-compiler/.1.3.3.19xoaaa.rbiig++os+web.browser+web.cordova/plugin.compileTemplatesBatch.os/npm/node_modules/meteor/caching-compiler/node_modules/async/lib/async.js:324:29
at
/home/sbarratt/.meteor/packages/templating-compiler/.1.3.3.19xoaaa.rbiig++os+web.browser+web.cordova/plugin.compileTemplatesBatch.os/npm/node_modules/meteor/caching-compiler/node_modules/async/lib/async.js:44:16
at packages/caching-compiler/caching-compiler.js:316:9
at
/home/sbarratt/.meteor/packages/templating-compiler/.1.3.3.19xoaaa.rbiig++os+web.browser+web.cordova/plugin.compileTemplatesBatch.os/npm/node_modules/meteor/caching-compiler/node_modules/async/lib/async.js:182:20
at replenish
(/home/sbarratt/.meteor/packages/templating-compiler/.1.3.3.19xoaaa.rbiig++os+web.browser+web.cordova/plugin.compileTemplatesBatch.os/npm/node_modules/meteor/caching-compiler/node_modules/async/lib/async.js:317:21)
at
/home/sbarratt/.meteor/packages/templating-compiler/.1.3.3.19xoaaa.rbiig++os+web.browser+web.cordova/plugin.compileTemplatesBatch.os/npm/node_modules/meteor/caching-compiler/node_modules/async/lib/async.js:324:29
at
/home/sbarratt/.meteor/packages/templating-compiler/.1.3.3.19xoaaa.rbiig++os+web.browser+web.cordova/plugin.compileTemplatesBatch.os/npm/node_modules/meteor/caching-compiler/node_modules/async/lib/async.js:44:16
at packages/caching-compiler/caching-compiler.js:316:9
at
/home/sbarratt/.meteor/packages/templating-compiler/.1.3.3.19xoaaa.rbiig++os+web.browser+web.cordova/plugin.compileTemplatesBatch.os/npm/node_modules/meteor/caching-compiler/node_modules/async/lib/async.js:182:20
at replenish
(/home/sbarratt/.meteor/packages/templating-compiler/.1.3.3.19xoaaa.rbiig++os+web.browser+web.cordova/plugin.compileTemplatesBatch.os/npm/node_modules/meteor/caching-compiler/node_modules/async/lib/async.js:317:21)
at
/home/sbarratt/.meteor/packages/templating-compiler/.1.3.3.19xoaaa.rbiig++os+web.browser+web.cordova/plugin.compileTemplatesBatch.os/npm/node_modules/meteor/caching-compiler/node_modules/async/lib/async.js:324:29
at
/home/sbarratt/.meteor/packages/templating-compiler/.1.3.3.19xoaaa.rbiig++os+web.browser+web.cordova/plugin.compileTemplatesBatch.os/npm/node_modules/meteor/caching-compiler/node_modules/async/lib/async.js:44:16
at packages/caching-compiler/caching-compiler.js:316:9
at
/home/sbarratt/.meteor/packages/templating-compiler/.1.3.3.19xoaaa.rbiig++os+web.browser+web.cordova/plugin.compileTemplatesBatch.os/npm/node_modules/meteor/caching-compiler/node_modules/async/lib/async.js:182:20
at replenish
(/home/sbarratt/.meteor/packages/templating-compiler/.1.3.3.19xoaaa.rbiig++os+web.browser+web.cordova/plugin.compileTemplatesBatch.os/npm/node_modules/meteor/caching-compiler/node_modules/async/lib/async.js:317:21)
at
/home/sbarratt/.meteor/packages/templating-compiler/.1.3.3.19xoaaa.rbiig++os+web.browser+web.cordova/plugin.compileTemplatesBatch.os/npm/node_modules/meteor/caching-compiler/node_modules/async/lib/async.js:324:29
at
/home/sbarratt/.meteor/packages/templating-compiler/.1.3.3.19xoaaa.rbiig++os+web.browser+web.cordova/plugin.compileTemplatesBatch.os/npm/node_modules/meteor/caching-compiler/node_modules/async/lib/async.js:44:16
at packages/caching-compiler/caching-compiler.js:316:9
at
/home/sbarratt/.meteor/packages/templating-compiler/.1.3.3.19xoaaa.rbiig++os+web.browser+web.cordova/plugin.compileTemplatesBatch.os/npm/node_modules/meteor/caching-compiler/node_modules/async/lib/async.js:182:20
at replenish
(/home/sbarratt/.meteor/packages/templating-compiler/.1.3.3.19xoaaa.rbiig++os+web.browser+web.cordova/plugin.compileTemplatesBatch.os/npm/node_modules/meteor/caching-compiler/node_modules/async/lib/async.js:317:21)
at
/home/sbarratt/.meteor/packages/templating-compiler/.1.3.3.19xoaaa.rbiig++os+web.browser+web.cordova/plugin.compileTemplatesBatch.os/npm/node_modules/meteor/caching-compiler/node_modules/async/lib/async.js:328:15
at Object.async.forEachLimit.async.eachLimit
(/home/sbarratt/.meteor/packages/templating-compiler/.1.3.3.19xoaaa.rbiig++os+web.browser+web.cordova/plugin.compileTemplatesBatch.os/npm/node_modules/meteor/caching-compiler/node_modules/async/lib/async.js:221:35)
at CachingHtmlCompiler.processFilesForTarget (packages/caching-compiler/caching-compiler.js:284:11)
at CachingHtmlCompiler.processFilesForTarget (packages/caching-html-compiler/caching-html-compiler.js:40:5)
```

**Comment by fabioaraujo121** [comment]
I had the same issue and solved by adding the akryum:vue package.
`meteor add akryum:vue`
Hope it helps!

**Comment by gustawdaniel** [comment]
How to fix?

https://vuejs.org/v2/cookbook/practical-use-of-scoped-slots.html
