### ISSUE TITLE
component error

### ISSUE THREAD

**Issue by mehrdadphp** [meteor-vue/vue-meteor#308]
#Hi
I can not run a componente with the following error

Errors prevented startup:

While processing files with akryum:vue-component (for target web.browser):
packages/vue-component/plugin/vue-compiler.js:550:44: Cannot read property 'parseComponent' of undefined
  at compileOneFileWithContents (packages/vue-component/plugin/vue-compiler.js:550:44)
  at VueCompo.compileOneFile (packages/vue-component/plugin/vue-compiler.js:140:12)
  at async.eachLimit (packages/vue-component/plugin/vue-compiler.js:57:34)
  at /home/mehrdad/.meteor/packages/akryum_vue-component/.0.13.1.152jvbc.un7y++os+web.browser+web.cordova/plugin.vue-component.os/npm/node_modules/meteor/vue-component/node_modules/async/dist/async.js:3096:16
  at replenish (/home/mehrdad/.meteor/packages/akryum_vue-component/.0.13.1.152jvbc.un7y++os+web.browser+web.cordova/plugin.vue-component.os/npm/node_modules/meteor/vue-component/node_modules/async/dist/async.js:998:17)
  at /home/mehrdad/.meteor/packages/akryum_vue-component/.0.13.1.152jvbc.un7y++os+web.browser+web.cordova/plugin.vue-component.os/npm/node_modules/meteor/vue-component/node_modules/async/dist/async.js:1002:9
  at Object.eachLimit$1 (/home/mehrdad/.meteor/packages/akryum_vue-component/.0.13.1.152jvbc.un7y++os+web.browser+web.cordova/plugin.vue-component.os/npm/node_modules/meteor/vue-component/node_modules/async/dist/async.js:3182:24)
  at VueCompo.processFilesForTarget (packages/vue-component/plugin/vue-compiler.js:41:11)

While processing files with akryum:vue-component (for target os.linux.x86_64):
packages/vue-component/plugin/vue-compiler.js:550:44: Cannot read property 'parseComponent' of undefined
  at compileOneFileWithContents (packages/vue-component/plugin/vue-compiler.js:550:44)
  at VueCompo.compileOneFile (packages/vue-component/plugin/vue-compiler.js:140:12)
  at async.eachLimit (packages/vue-component/plugin/vue-compiler.js:57:34)
  at /home/mehrdad/.meteor/packages/akryum_vue-component/.0.13.1.152jvbc.un7y++os+web.browser+web.cordova/plugin.vue-component.os/npm/node_modules/meteor/vue-component/node_modules/async/dist/async.js:3096:16
  at replenish (/home/mehrdad/.meteor/packages/akryum_vue-component/.0.13.1.152jvbc.un7y++os+web.browser+web.cordova/plugin.vue-component.os/npm/node_modules/meteor/vue-component/node_modules/async/dist/async.js:998:17)
  at /home/mehrdad/.meteor/packages/akryum_vue-component/.0.13.1.152jvbc.un7y++os+web.browser+web.cordova/plugin.vue-component.os/npm/node_modules/meteor/vue-component/node_modules/async/dist/async.js:1002:9
  at Object.eachLimit$1 (/home/mehrdad/.meteor/packages/akryum_vue-component/.0.13.1.152jvbc.un7y++os+web.browser+web.cordova/plugin.vue-component.os/npm/node_modules/meteor/vue-component/node_modules/async/dist/async.js:3182:24)
  at VueCompo.processFilesForTarget (packages/vue-component/plugin/vue-compiler.js:41:11)

Your application has errors. Waiting for file change.

**Comment by cuginoAle** [comment]
Same here!
Tried the following:

- meteor create --bare meteor-vue
- cd meteor-vue
- meteor remove blaze-templates reactive-var
- meteor add static-html akryum:vue-component akryum:vue-ssr
- meteor

same error, any suggestion?

thanks

**Comment by gustawdaniel** [comment]
I applied commands:

```
meteor remove blaze-templates reactive-var
meteor add static-html akryum:vue-component akryum:vue-ssr 
```

And saw error:

```
  While determining active plugins:
   error: conflict: two packages included in the app (templating-compiler and static-html) are both
   trying to handle *.html
```

I typed also

```
meteor remove blaze-html-templates                                              
```

And still have the same error.

I was using this tutorial:

> https://github.com/Akryum/meteor-vue-example

**Comment by DirkStevens** [comment]
Looks like it's a problem with the documentation?
After I installed vue manually with "meteor npm install --save vue@2.5.16." the problem disappeared.
