### ISSUE TITLE
Error while compiling in tag <script>: Cannot find module 'babel-preset-env'

### ISSUE THREAD

**Issue by DirkStevens** [meteor-vue/vue-meteor#320]
Following error occurs when importing a "component.vue" that is located in my /imports folder:

" [vue-component] Error while compiling in tag <script>: Cannot find module 'babel-preset-env' from <Meteor project root> "

Meteor project is at 1.6.1.1

- Added the akryum:vue-component package
- Removed all content from node_modules: in node_modules -> rm -rf *
- meteor update
- meteor npm install
- Added vue with meteor npm install --save vue

Anyone any idea what could be going wrong?

**Comment by Akryum** [comment]
What is the content of your `.babelrc` file?

**Comment by DirkStevens** [comment]
There's no .babelrc file...

**Comment by DirkStevens** [comment]
My package.json contains:

  "babel": {
    "presets": [
      "env"
    ]
  },

**Comment by Akryum** [comment]
Remove this and you should be fine.

**Comment by DirkStevens** [comment]
Thanks, looks like we're a step further, now I'm getting an error:
Error: Cannot find module '@babel/runtime/helpers/builtin/objectSpread'
W20180520-13:11:39.307(2)? (STDERR)     at Function.Module._resolveFilename (module.js:547:15)
W20180520-13:11:39.307(2)? (STDERR)     at Function.resolve (internal/module.js:18:19)

**Comment by Akryum** [comment]
Make sure you don't use any old `babel-runtime` package (check in `package.json`) and make sure you have the latest `@babel/runtime` package installed:

```
meteor npm i @babel/runtime@latest
```
