### ISSUE TITLE
Get error when`@import '~imports/client/styles/main.scss'` in Meteor1.7!

### ISSUE THREAD

**Issue by thearabbit** [meteor-vue/vue-meteor#327]
I tried to use Meteor1.7 + Vue Compoent + Vue Sass.
My code
```
<template>
  <h1 class="testing">Welcome to Meteor 1.7 + Vue</h1>
</template>

<script>
export default {
  name: 'App',
}
</script>

<style lang="scss" scoped>
@import '~imports/client/styles/main.scss';
</style>
```
Get error
```
=> Client modified -- refreshingmeteor://💻app/packages/vue-component-sass_plugin.js:51
    url = url.replace(/^["']?(.*?)["']?$/, '$1');
              ^

TypeError: url.replace is not a function
    at Object.<anonymous> (packages/vue-component-sass/vue-sass.js:12:15)
    at options.importer (/Users/theara/.meteor/packages/akryum_vue-sass/.0.1.0.168z2n7.9v0l++os+web.browser+web.cordova/plugin.vue-component-sass.os/npm/node_modules/meteor/vue-component-sass/node_modules/node-sass/lib/index.js:336:31
```

**Comment by thearabbit** [comment]
I work fine when I try remove `fourseven:scss`
