### ISSUE TITLE
Get erro `Vue-component 0.14.1 + METEOR@1.7.0.5`

### ISSUE THREAD

**Issue by thearabbit** [meteor-vue/vue-meteor#337]
```js
Compiling /Users/theara/Desktop/meteor-app/meteor-element3/node_modules/element-ui/packages/color-picker/src/components/alpha-slider.vue with meteor-babel without a cache
[object Object]
    at Object.exports.compile (/Users/theara/.meteor/packages/akryum_vue-component/.0.14.1.1dgcljj.ts7mh++os+web.browser+web.browser.legacy+web.cordova/plugin.vue-component.os/npm/node_modules/meteor/babel-compiler/node_modules/meteor-babel/index.js:77:13)
    at Object.compile (packages/babel-compiler.js:44:29)
    at VueComponentTagHandler.getResults (packages/vue-component/plugin/tag-handler.js:128:30)
    at compileTags (packages/vue-component/plugin/vue-compiler.js:540:18)
    at compileOneFileWithContents (packages/vue-component/plugin/vue-compiler.js:549:12)
    at VueCompo.compileOneFile (packages/vue-component/plugin/vue-compiler.js:137:12)
    at async.eachLimit (packages/vue-component/plugin/vue-compiler.js:54:34)
    at /Users/theara/.meteor/packages/akryum_vue-component/.0.14.1.1dgcljj.ts7mh++os+web.browser+web.browser.legacy+web.cordova/plugin.vue-component.os/npm/node_modules/meteor/vue-component/node_modules/async/dist/async.js:3096:16
    at replenish (/Users/theara/.meteor/packages/akryum_vue-component/.0.14.1.1dgcljj.ts7mh++os+web.browser+web.browser.legacy+web.cordova/plugin.vue-component.os/npm/node_modules/meteor/vue-component/node_modules/async/dist/async.js:998:17)
    at /Users/theara/.meteor/packages/akryum_vue-component/.0.14.1.1dgcljj.ts7mh++os+web.browser+web.browser.legacy+web.cordova/plugin.vue-component.os/npm/node_modules/meteor/vue-component/node_modules/async/dist/async.js:1002:9
    at Object.eachLimit$1 (/Users/theara/.meteor/packages/akryum_vue-component/.0.14.1.1dgcljj.ts7mh++os+web.browser+web.browser.legacy+web.cordova/plugin.vue-component.os/npm/node_modules/meteor/vue-component/node_modules/async/dist/async.js:3182:24)
    at VueCompo.processFilesForTarget (packages/vue-component/plugin/vue-compiler.js:38:11)
    at __bottom_mark__ (/tools/utils/parse-stack.js:64:14)
```

**Comment by DirkStevens** [comment]
Same problem...

Compiling /Users/dirkstevens/Surveywonders/Suazio/app/imports/lib/wondergraphs/lib/wLegend.vue with meteor-babel without a cache
[object Object]
    at Object.exports.compile (/Users/dirkstevens/.meteor/packages/akryum_vue-component/.0.14.1.aslzhk.fy4ou++os+web.browser+web.browser.legacy+web.cordova/plugin.vue-component.os/npm/node_modules/meteor/babel-compiler/node_modules/meteor-babel/index.js:77:13)
    at Object.compile (packages/babel-compiler.js:44:29)
    at VueComponentTagHandler.getResults (packages/vue-component/plugin/tag-handler.js:128:30)
    at compileTags (packages/vue-component/plugin/vue-compiler.js:540:18)
    at compileOneFileWithContents (packages/vue-component/plugin/vue-compiler.js:549:12)
    at VueCompo.compileOneFile (packages/vue-component/plugin/vue-compiler.js:137:12)
    at async.eachLimit (packages/vue-component/plugin/vue-compiler.js:54:34)
    at /Users/dirkstevens/.meteor/packages/akryum_vue-component/.0.14.1.aslzhk.fy4ou++os+web.browser+web.browser.legacy+web.cordova/plugin.vue-component.os/npm/node_modules/meteor/vue-component/node_modules/async/dist/async.js:3096:16
    at replenish (/Users/dirkstevens/.meteor/packages/akryum_vue-component/.0.14.1.aslzhk.fy4ou++os+web.browser+web.browser.legacy+web.cordova/plugin.vue-component.os/npm/node_modules/meteor/vue-component/node_modules/async/dist/async.js:998:17)
    at iterateeCallback (/Users/dirkstevens/.meteor/packages/akryum_vue-component/.0.14.1.aslzhk.fy4ou++os+web.browser+web.browser.legacy+web.cordova/plugin.vue-component.os/npm/node_modules/meteor/vue-component/node_modules/async/dist/async.js:983:17)
    at /Users/dirkstevens/.meteor/packages/akryum_vue-component/.0.14.1.aslzhk.fy4ou++os+web.browser+web.browser.legacy+web.cordova/plugin.vue-component.os/npm/node_modules/meteor/vue-component/node_modules/async/dist/async.js:958:16
    at async.eachLimit (packages/vue-component/plugin/vue-compiler.js:71:11)
    at /Users/dirkstevens/.meteor/packages/akryum_vue-component/.0.14.1.aslzhk.fy4ou++os+web.browser+web.browser.legacy+web.cordova/plugin.vue-component.os/npm/node_modules/meteor/vue-component/node_modules/async/dist/async.js:3096:16

**Comment by DirkStevens** [comment]
@thearabbit The compile without a cache problem is fixed with @ch-lukas PR:
https://github.com/meteor-vue/vue-meteor/pull/338

However I'm still getting:
`/Users/retro/.meteor/packages/meteor-tool/.1.8.0.11zn2tw.7g5h++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:218
      throw error;
      ^
undefined
 => awaited here:
    at Promise.await (/Users/retro/.meteor/packages/meteor-tool/.1.8.0.11zn2tw.7g5h++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:60:12)
    at JsOutputResource.finalize (/tools/isobuild/compiler-plugin.js:891:7)
    at JsOutputResource.hasPendingErrors (/tools/isobuild/compiler-plugin.js:918:10)
    at JsOutputResource.reportPendingErrors (/tools/isobuild/compiler-plugin.js:923:14)
    at ImportScanner._scanFile (/tools/isobuild/import-scanner.js:849:14)
    at each (/tools/isobuild/import-scanner.js:907:14)
    at _.each._.forEach (/Users/retro/.meteor/packages/meteor-tool/.1.8.0.11zn2tw.7g5h++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:87:22)
    at ImportScanner._scanFile (/tools/isobuild/import-scanner.js:871:5)
    at each (/tools/isobuild/import-scanner.js:907:14)
    at _.each._.forEach (/Users/retro/.meteor/packages/meteor-tool/.1.8.0.11zn2tw.7g5h++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:87:22)
    at ImportScanner._scanFile (/tools/isobuild/import-scanner.js:871:5)
    at each (/tools/isobuild/import-scanner.js:907:14)`

**Comment by thearabbit** [comment]
now I used `vue-Component 0.14.0 + Meteor 1.7.0.5`

**Comment by chris-visser** [comment]
The latest version of this package contains the fix @thearabbit

**Comment by thearabbit** [comment]
Good
