### ISSUE TITLE
Error while starting meteor: Unknown browser query `dead`

### ISSUE THREAD

**Issue by WayneUong** [meteor-vue/vue-meteor#345]
```
   While processing files with akryum:vue-component (for target web.browser):

   /Users/wayneuong/.meteor/packages/akryum_vue-component/.0.14.3.1mashqe.ze11++os+web.browser+web.browser.legacy+web.cordova/plugin.vue-component.os/npm/node_modules/meteor/vue-component/node_modules/browserslist/index.js:164:11:
   Unknown browser query `dead`
   at
   /Users/wayneuong/.meteor/packages/akryum_vue-component/.0.14.3.1mashqe.ze11++os+web.browser+web.browser.legacy+web.cordova/plugin.vue-component.os/npm/node_modules/meteor/vue-component/node_modules/browserslist/index.js:164:11
   at Array.reduce (<anonymous>)
   at resolve
   (/Users/wayneuong/.meteor/packages/akryum_vue-component/.0.14.3.1mashqe.ze11++os+web.browser+web.browser.legacy+web.cordova/plugin.vue-component.os/npm/node_modules/meteor/vue-component/node_modules/browserslist/index.js:132:18)
   at browserslist
   (/Users/wayneuong/.meteor/packages/akryum_vue-component/.0.14.3.1mashqe.ze11++os+web.browser+web.browser.legacy+web.cordova/plugin.vue-component.os/npm/node_modules/meteor/vue-component/node_modules/browserslist/index.js:224:16)
   at Browsers.parse
   (/Users/wayneuong/.meteor/packages/akryum_vue-component/.0.14.3.1mashqe.ze11++os+web.browser+web.browser.legacy+web.cordova/plugin.vue-component.os/npm/node_modules/meteor/vue-component/node_modules/autoprefixer/lib/browsers.js:61:16)
   at new Browsers
   (/Users/wayneuong/.meteor/packages/akryum_vue-component/.0.14.3.1mashqe.ze11++os+web.browser+web.browser.legacy+web.cordova/plugin.vue-component.os/npm/node_modules/meteor/vue-component/node_modules/autoprefixer/lib/browsers.js:52:30)
   at loadPrefixes
   (/Users/wayneuong/.meteor/packages/akryum_vue-component/.0.14.3.1mashqe.ze11++os+web.browser+web.browser.legacy+web.cordova/plugin.vue-component.os/npm/node_modules/meteor/vue-component/node_modules/autoprefixer/lib/autoprefixer.js:70:24)
   at plugin
   (/Users/wayneuong/.meteor/packages/akryum_vue-component/.0.14.3.1mashqe.ze11++os+web.browser+web.browser.legacy+web.cordova/plugin.vue-component.os/npm/node_modules/meteor/vue-component/node_modules/autoprefixer/lib/autoprefixer.js:81:24)
   at LazyResult.run (lazy-result.es6:331:20)
   at LazyResult.sync (lazy-result.es6:317:32)
   at LazyResult.stringify (lazy-result.es6:342:14)
   at LazyResult.get (lazy-result.es6:81:21)
   at VueComponentTagHandler.getResults (packages/vue-component/plugin/tag-handler.js:382:22)
   at compileTags (packages/vue-component/plugin/vue-compiler.js:532:18)
   at compileOneFileWithContents (packages/vue-component/plugin/vue-compiler.js:541:12)
   at VueCompo.compileOneFile (packages/vue-component/plugin/vue-compiler.js:140:12)
   at async.eachLimit (packages/vue-component/plugin/vue-compiler.js:57:34)
   at
   /Users/wayneuong/.meteor/packages/akryum_vue-component/.0.14.3.1mashqe.ze11++os+web.browser+web.browser.legacy+web.cordova/plugin.vue-component.os/npm/node_modules/meteor/vue-component/node_modules/async/dist/async.js:3096:16
   at replenish
   (/Users/wayneuong/.meteor/packages/akryum_vue-component/.0.14.3.1mashqe.ze11++os+web.browser+web.browser.legacy+web.cordova/plugin.vue-component.os/npm/node_modules/meteor/vue-component/node_modules/async/dist/async.js:998:17)
   at iterateeCallback
   (/Users/wayneuong/.meteor/packages/akryum_vue-component/.0.14.3.1mashqe.ze11++os+web.browser+web.browser.legacy+web.cordova/plugin.vue-component.os/npm/node_modules/meteor/vue-component/node_modules/async/dist/async.js:983:17)
   at
   /Users/wayneuong/.meteor/packages/akryum_vue-component/.0.14.3.1mashqe.ze11++os+web.browser+web.browser.legacy+web.cordova/plugin.vue-component.os/npm/node_modules/meteor/vue-component/node_modules/async/dist/async.js:958:16
   at async.eachLimit (packages/vue-component/plugin/vue-compiler.js:74:11)
   at
   /Users/wayneuong/.meteor/packages/akryum_vue-component/.0.14.3.1mashqe.ze11++os+web.browser+web.browser.legacy+web.cordova/plugin.vue-component.os/npm/node_modules/meteor/vue-component/node_modules/async/dist/async.js:3096:16
   at replenish
   (/Users/wayneuong/.meteor/packages/akryum_vue-component/.0.14.3.1mashqe.ze11++os+web.browser+web.browser.legacy+web.cordova/plugin.vue-component.os/npm/node_modules/meteor/vue-component/node_modules/async/dist/async.js:998:17)
   at iterateeCallback
   (/Users/wayneuong/.meteor/packages/akryum_vue-component/.0.14.3.1mashqe.ze11++os+web.browser+web.browser.legacy+web.cordova/plugin.vue-component.os/npm/node_modules/meteor/vue-component/node_modules/async/dist/async.js:983:17)
   at
   /Users/wayneuong/.meteor/packages/akryum_vue-component/.0.14.3.1mashqe.ze11++os+web.browser+web.browser.legacy+web.cordova/plugin.vue-component.os/npm/node_modules/meteor/vue-component/node_modules/async/dist/async.js:958:16
   at async.eachLimit (packages/vue-component/plugin/vue-compiler.js:74:11)
   at
   /Users/wayneuong/.meteor/packages/akryum_vue-component/.0.14.3.1mashqe.ze11++os+web.browser+web.browser.legacy+web.cordova/plugin.vue-component.os/npm/node_modules/meteor/vue-component/node_modules/async/dist/async.js:3096:16
   at replenish
```

Error keeps going...

**Comment by WayneUong** [comment]
@Akryum You can run this repo to see the error. Clone this and run with meteor: https://github.com/WayneUong/vue-modal-error

Steps to reproduce:
```
meteor create --bare vue-modal-error
cd vue-modal-error
meteor add akryum:vue-component
meteor npm i -S vue-js-modal
meteor
```

You should get this error:
```
   While processing files with akryum:vue-component (for target web.browser):
   /Users/wayneuong/.meteor/packages/akryum_vue-component/.0.14.3.1mashqe.ze11++os+web.browser+web.browser.legacy+web.cordova/plugin.vue-component.os/npm/node_modules/meteor/vue-component/node_modules/browserslist/index.js:164:11: Unknown browser query `dead`
   at /Users/wayneuong/.meteor/packages/akryum_vue-component/.0.14.3.1mashqe.ze11++os+web.browser+web.browser.legacy+web.cordova/plugin.vue-component.os/npm/node_modules/meteor/vue-component/node_modules/browserslist/index.js:164:11
   at Array.reduce (<anonymous>)
   at resolve (/Users/wayneuong/.meteor/packages/akryum_vue-component/.0.14.3.1mashqe.ze11++os+web.browser+web.browser.legacy+web.cordova/plugin.vue-component.os/npm/node_modules/meteor/vue-component/node_modules/browserslist/index.js:132:18)
   at browserslist (/Users/wayneuong/.meteor/packages/akryum_vue-component/.0.14.3.1mashqe.ze11++os+web.browser+web.browser.legacy+web.cordova/plugin.vue-component.os/npm/node_modules/meteor/vue-component/node_modules/browserslist/index.js:224:16)
   at Browsers.parse (/Users/wayneuong/.meteor/packages/akryum_vue-component/.0.14.3.1mashqe.ze11++os+web.browser+web.browser.legacy+web.cordova/plugin.vue-component.os/npm/node_modules/meteor/vue-component/node_modules/autoprefixer/lib/browsers.js:61:16)
   at new Browsers (/Users/wayneuong/.meteor/packages/akryum_vue-component/.0.14.3.1mashqe.ze11++os+web.browser+web.browser.legacy+web.cordova/plugin.vue-component.os/npm/node_modules/meteor/vue-component/node_modules/autoprefixer/lib/browsers.js:52:30)
   at loadPrefixes (/Users/wayneuong/.meteor/packages/akryum_vue-component/.0.14.3.1mashqe.ze11++os+web.browser+web.browser.legacy+web.cordova/plugin.vue-component.os/npm/node_modules/meteor/vue-component/node_modules/autoprefixer/lib/autoprefixer.js:70:24)
   at plugin (/Users/wayneuong/.meteor/packages/akryum_vue-component/.0.14.3.1mashqe.ze11++os+web.browser+web.browser.legacy+web.cordova/plugin.vue-component.os/npm/node_modules/meteor/vue-component/node_modules/autoprefixer/lib/autoprefixer.js:81:24)
   at LazyResult.run (lazy-result.es6:331:20)
   at LazyResult.sync (lazy-result.es6:317:32)
   at LazyResult.stringify (lazy-result.es6:342:14)
   at LazyResult.get (lazy-result.es6:81:21)
   at VueComponentTagHandler.getResults (packages/vue-component/plugin/tag-handler.js:382:22)
   at compileTags (packages/vue-component/plugin/vue-compiler.js:532:18)
   at compileOneFileWithContents (packages/vue-component/plugin/vue-compiler.js:541:12)
   at VueCompo.compileOneFile (packages/vue-component/plugin/vue-compiler.js:140:12)
   at async.eachLimit (packages/vue-component/plugin/vue-compiler.js:57:34)
   at /Users/wayneuong/.meteor/packages/akryum_vue-component/.0.14.3.1mashqe.ze11++os+web.browser+web.browser.legacy+web.cordova/plugin.vue-component.os/npm/node_modules/meteor/vue-component/node_modules/async/dist/async.js:3096:16
   at replenish (/Users/wayneuong/.meteor/packages/akryum_vue-component/.0.14.3.1mashqe.ze11++os+web.browser+web.browser.legacy+web.cordova/plugin.vue-component.os/npm/node_modules/meteor/vue-component/node_modules/async/dist/async.js:998:17)
   at /Users/wayneuong/.meteor/packages/akryum_vue-component/.0.14.3.1mashqe.ze11++os+web.browser+web.browser.legacy+web.cordova/plugin.vue-component.os/npm/node_modules/meteor/vue-component/node_modules/async/dist/async.js:1002:9
   at Object.eachLimit$1 (/Users/wayneuong/.meteor/packages/akryum_vue-component/.0.14.3.1mashqe.ze11++os+web.browser+web.browser.legacy+web.cordova/plugin.vue-component.os/npm/node_modules/meteor/vue-component/node_modules/async/dist/async.js:3182:24)
   at VueCompo.processFilesForTarget (packages/vue-component/plugin/vue-compiler.js:41:11)
```

**Comment by karlitos** [comment]
Any solution or workaround to this ?
