### ISSUE TITLE
Error i all my Meteor vue projects after upgrade to 1.8

### ISSUE THREAD

**Issue by thor-n** [meteor-vue/vue-meteor#354]
> Errors prevented startup:

   While processing files with akryum:vue-router2 (for target web.browser):

   C:\Users\tbn\AppData\Local\.meteor\packages\akryum_vue-router2\0.2.2\plugin.vue-router.os\npm\node_modules\meteor\babel-compiler\node_modules\@babel\core\lib\config\validation\options.js:123:11:
   .sourceMap is an alias for .sourceMaps, cannot use both
   at assertNoDuplicateSourcemap
   (C:\Users\tbn\AppData\Local\.meteor\packages\akryum_vue-router2\0.2.2\plugin.vue-router.os\npm\node_modules\meteor\babel-compiler\node_modules\@babel\core\lib\config\validation\options.js:123:11)
   at validate
   (C:\Users\tbn\AppData\Local\.meteor\packages\akryum_vue-router2\0.2.2\plugin.vue-router.os\npm\node_modules\meteor\babel-compiler\node_modules\@babel\core\lib\config\validation\options.js:68:3)
   at loadPrivatePartialConfig
   (C:\Users\tbn\AppData\Local\.meteor\packages\akryum_vue-router2\0.2.2\plugin.vue-router.os\npm\node_modules\meteor\babel-compiler\node_modules\@babel\core\lib\config\partial.js:38:50)
   at loadFullConfig
   (C:\Users\tbn\AppData\Local\.meteor\packages\akryum_vue-router2\0.2.2\plugin.vue-router.os\npm\node_modules\meteor\babel-compiler\node_modules\@babel\core\lib\config\full.js:43:39)
   at Object.transformSync
   (C:\Users\tbn\AppData\Local\.meteor\packages\akryum_vue-router2\0.2.2\plugin.vue-router.os\npm\node_modules\meteor\babel-compiler\node_modules\@babel\core\lib\transform.js:41:38)
   at transform
   (C:\Users\tbn\AppData\Local\.meteor\packages\akryum_vue-router2\0.2.2\plugin.vue-router.os\npm\node_modules\meteor\babel-compiler\node_modules\meteor-babel\index.js:103:26)
   at compile
   (C:\Users\tbn\AppData\Local\.meteor\packages\akryum_vue-router2\0.2.2\plugin.vue-router.os\npm\node_modules\meteor\babel-compiler\node_modules\meteor-babel\index.js:122:5)
   at Cache.Cp.get
   (C:\Users\tbn\AppData\Local\.meteor\packages\akryum_vue-router2\0.2.2\plugin.vue-router.os\npm\node_modules\meteor\babel-compiler\node_modules\meteor-babel\cache.js:101:26)
   at Object.exports.compile
   (C:\Users\tbn\AppData\Local\.meteor\packages\akryum_vue-router2\0.2.2\plugin.vue-router.os\npm\node_modules\meteor\babel-compiler\node_modules\meteor-babel\index.js:63:8)
   at Object.compile (packages/babel-compiler.js:44:29)
   at VueRouterCompiler.compileOneFile (packages/vue-router/plugin/plugin.js:46:24)
   at async.eachLimit (packages/caching-compiler/caching-compiler.js:306:32)
   at
   C:\Users\tbn\AppData\Local\.meteor\packages\akryum_vue-router2\0.2.2\plugin.vue-router.os\npm\node_modules\meteor\caching-compiler\node_modules\async\lib\async.js:182:20
   at replenish
   (C:\Users\tbn\AppData\Local\.meteor\packages\akryum_vue-router2\0.2.2\plugin.vue-router.os\npm\node_modules\meteor\caching-compiler\node_modules\async\lib\async.js:317:21)
   at
   C:\Users\tbn\AppData\Local\.meteor\packages\akryum_vue-router2\0.2.2\plugin.vue-router.os\npm\node_modules\meteor\caching-compiler\node_modules\async\lib\async.js:328:15
   at Object.async.forEachLimit.async.eachLimit
   (C:\Users\tbn\AppData\Local\.meteor\packages\akryum_vue-router2\0.2.2\plugin.vue-router.os\npm\node_modules\meteor\caching-compiler\node_modules\async\lib\async.js:221:35)
   at VueRouterCompiler.processFilesForTarget (packages/caching-compiler/caching-compiler.js:287:11)

   While processing files with akryum:vue-router2 (for target web.browser.legacy):

   C:\Users\tbn\AppData\Local\.meteor\packages\akryum_vue-router2\0.2.2\plugin.vue-router.os\npm\node_modules\meteor\babel-compiler\node_modules\@babel\core\lib\config\validation\options.js:123:11:
   .sourceMap is an alias for .sourceMaps, cannot use both
   at assertNoDuplicateSourcemap
   (C:\Users\tbn\AppData\Local\.meteor\packages\akryum_vue-router2\0.2.2\plugin.vue-router.os\npm\node_modules\meteor\babel-compiler\node_modules\@babel\core\lib\config\validation\options.js:123:11)
   at validate
   (C:\Users\tbn\AppData\Local\.meteor\packages\akryum_vue-router2\0.2.2\plugin.vue-router.os\npm\node_modules\meteor\babel-compiler\node_modules\@babel\core\lib\config\validation\options.js:68:3)
   at loadPrivatePartialConfig
   (C:\Users\tbn\AppData\Local\.meteor\packages\akryum_vue-router2\0.2.2\plugin.vue-router.os\npm\node_modules\meteor\babel-compiler\node_modules\@babel\core\lib\config\partial.js:38:50)
   at loadFullConfig
   (C:\Users\tbn\AppData\Local\.meteor\packages\akryum_vue-router2\0.2.2\plugin.vue-router.os\npm\node_modules\meteor\babel-compiler\node_modules\@babel\core\lib\config\full.js:43:39)
   at Object.transformSync
   (C:\Users\tbn\AppData\Local\.meteor\packages\akryum_vue-router2\0.2.2\plugin.vue-router.os\npm\node_modules\meteor\babel-compiler\node_modules\@babel\core\lib\transform.js:41:38)
   at transform
   (C:\Users\tbn\AppData\Local\.meteor\packages\akryum_vue-router2\0.2.2\plugin.vue-router.os\npm\node_modules\meteor\babel-compiler\node_modules\meteor-babel\index.js:103:26)
   at compile
   (C:\Users\tbn\AppData\Local\.meteor\packages\akryum_vue-router2\0.2.2\plugin.vue-router.os\npm\node_modules\meteor\babel-compiler\node_modules\meteor-babel\index.js:122:5)
   at Cache.Cp.get
   (C:\Users\tbn\AppData\Local\.meteor\packages\akryum_vue-router2\0.2.2\plugin.vue-router.os\npm\node_modules\meteor\babel-compiler\node_modules\meteor-babel\cache.js:101:26)
   at Object.exports.compile
   (C:\Users\tbn\AppData\Local\.meteor\packages\akryum_vue-router2\0.2.2\plugin.vue-router.os\npm\node_modules\meteor\babel-compiler\node_modules\meteor-babel\index.js:63:8)
   at Object.compile (packages/babel-compiler.js:44:29)
   at VueRouterCompiler.compileOneFile (packages/vue-router/plugin/plugin.js:46:24)
   at async.eachLimit (packages/caching-compiler/caching-compiler.js:306:32)
   at
   C:\Users\tbn\AppData\Local\.meteor\packages\akryum_vue-router2\0.2.2\plugin.vue-router.os\npm\node_modules\meteor\caching-compiler\node_modules\async\lib\async.js:182:20
   at replenish
   (C:\Users\tbn\AppData\Local\.meteor\packages\akryum_vue-router2\0.2.2\plugin.vue-router.os\npm\node_modules\meteor\caching-compiler\node_modules\async\lib\async.js:317:21)
   at
   C:\Users\tbn\AppData\Local\.meteor\packages\akryum_vue-router2\0.2.2\plugin.vue-router.os\npm\node_modules\meteor\caching-compiler\node_modules\async\lib\async.js:328:15
   at Object.async.forEachLimit.async.eachLimit
   (C:\Users\tbn\AppData\Local\.meteor\packages\akryum_vue-router2\0.2.2\plugin.vue-router.os\npm\node_modules\meteor\caching-compiler\node_modules\async\lib\async.js:221:35)
   at VueRouterCompiler.processFilesForTarget (packages/caching-compiler/caching-compiler.js:287:11)

=> Your application has errors. Waiting for file change.

I can read that many have the same problem, any news about a solution? Please support akryum here https://www.patreon.com/akryum so we can get more update :)

**Comment by thor-n** [comment]
I found a fix:
Downgrade to akryum:vue-router2@=0.2.0 

And if mongodb says: Unexpected mongo exit code 62. Restarting.
Then: Meteor reset (delete local db content)

to @Akryum maybe a solution here : https://github.com/meteor-vue/vue-meteor/issues/336
