### ISSUE TITLE
After upgrading to akryum:vue-ssr@0.4.0 it cannot read property 'render' of undefined

### ISSUE THREAD

**Issue by jamgold** [meteor-vue/vue-meteor#365]
I just updated my vue-ssr project and now the whole site no longer works and breaks with the following error

```
TypeError: Cannot read property 'render' of undefined
    at normalizeRender (/Users/jhm/.meteor/packages/akryum_vue-ssr/.0.4.0.13hc8dv.nosi++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/vue-server-renderer/build.dev.js:8234:20)
    at render (/Users/jhm/.meteor/packages/akryum_vue-ssr/.0.4.0.13hc8dv.nosi++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/vue-server-renderer/build.dev.js:8638:5)
    at Object.renderToString (/Users/jhm/.meteor/packages/akryum_vue-ssr/.0.4.0.13hc8dv.nosi++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/vue-server-renderer/build.dev.js:9168:9)
    at asyncResult.then.app (packages/akryum:vue-ssr/server/index.js:104:20)
    at /Users/jhm/.meteor/packages/promise/.0.11.2.1nxo7hq++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/fiber_pool.js:43:40
```
these are the package versions with npm vue@2.6.10

```
akryum:vue-component@0.15.0
akryum:vue-component-dev-client@0.4.6
akryum:vue-component-dev-server@0.1.4
akryum:vue-ssr@0.4.0
```
Does anybody know how to fix this? Vue is also warning about
```
[Vue warn]: Invalid component name: "_ssrEscape". Component names should conform to valid custom element name in html5 specification.
```

**Comment by Neorama** [comment]
did you solve it?
