### ISSUE TITLE
Integrate Vuetify with VueJs and MeteorJs.

### ISSUE THREAD

**Issue by ajitgoel** [meteor-vue/vue-meteor#375]
I am sure that this might not be the right forum for this. Is there a way to integrate Vuetify into VueJs and MeteorJs so I can use its pre-build components. I have tried to install both Vuetify 1.5.19 and 2.1.7 using the [following forum comments ](https://forum.vuejs.org/t/how-to-install-vuetify-with-meteor/70888/8)but I get errors when I start the application up.  

```
PS C:\Temp\vuemeteor> meteor --settings settings.json
[[[[[ C:\Temp\vuemeteor ]]]]]

=> Started proxy.
=> [HMR] Dev server listening on port 3003.
=> Started MongoDB.
I20191027-09:50:04.063(-7)? tracker installed
W20191027-09:50:04.413(-7)? (STDERR) C:\Temp\vuemeteor\node_modules\vuetify\dist\vuetify.min.css:5
W20191027-09:50:04.414(-7)? (STDERR) */@-webkit-keyframes shake{59%{margin-left:0}60%,80%{margin-left:2px}70%,90%{margin-left:-2px}}@keyframes shake{59%{margin-left:0}60%,80%{margin-left:2px}70%,90%{margin-left:-2px}}.black{background-color:#000!important;border-color:#000!important}.black--text{color:#000!important;caret-color:#000!important}.white{background-color:#fff!important;border-color:#fff!important}.white--text{color:#fff!important;caret-color:#fff!important}.transparent{background-color:transparent!important;border-color:transparent!important}.transparent--text{color:transparent!important;caret-color:transparent!important}.red{background-color:#f44336!important;border-color:#f44336!important}.red--text{color:#f44336!important;caret-color:#f44336!important}.red.lighten-5{background-color:#ffebee!important;border-color:#ffebee!important}.red--text.text--lighten-5{color:#ffebee!important;caret-color:#ffebee!important}.red.lighten-4{background-color:#ffcdd2!important;border-c
W20191027-09:50:04.425(-7)? (STDERR) 
W20191027-09:50:04.426(-7)? (STDERR) SyntaxError: Invalid or unexpected token
W20191027-09:50:04.427(-7)? (STDERR)     at createScript (vm.js:80:10)
W20191027-09:50:04.429(-7)? (STDERR)     at Object.runInThisContext (vm.js:139:10)
W20191027-09:50:04.430(-7)? (STDERR)     at Module._compile (module.js:617:28)
W20191027-09:50:04.430(-7)? (STDERR)     at Object.Module._extensions..js (module.js:664:10)
W20191027-09:50:04.431(-7)? (STDERR)     at Module.load (module.js:566:32)
W20191027-09:50:04.432(-7)? (STDERR)     at Function.Module._load (module.js:498:3)
W20191027-09:50:04.432(-7)? (STDERR)     at Module.require (module.js:597:17)
W20191027-09:50:04.432(-7)? (STDERR)     at require (internal/module.js:11:18)
W20191027-09:50:04.449(-7)? (STDERR)     at npmRequire (C:\Temp\vuemeteor\.meteor\local\build\programs\server\npm-require.js:133:10)
W20191027-09:50:04.461(-7)? (STDERR)     at Module.useNode (packages\modules-runtime.js:664:18)
W20191027-09:50:04.464(-7)? (STDERR)     at vuetify.min.css (packages\modules.js:752:8)
W20191027-09:50:04.465(-7)? (STDERR)     at fileEvaluate (packages\modules-runtime.js:336:7)
W20191027-09:50:04.487(-7)? (STDERR)     at Module.require (packages\modules-runtime.js:238:14)
W20191027-09:50:04.488(-7)? (STDERR)     at Module.moduleLink [as link] (C:\Users\ajitg\AppData\Local\.meteor\packages\modules\0.13.0\npm\node_modules\reify\lib\runtime\index.js:38:38)
W20191027-09:50:04.489(-7)? (STDERR)     at app.js (src/imports/app.js:1:1)
W20191027-09:50:04.490(-7)? (STDERR)     at fileEvaluate (packages\modules-runtime.js:336:7)
W20191027-09:50:04.490(-7)? (STDERR)     at Module.require (packages\modules-runtime.js:238:14)
W20191027-09:50:04.490(-7)? (STDERR)     at Module.moduleLink [as link] (C:\Users\ajitg\AppData\Local\.meteor\packages\modules\0.13.0\npm\node_modules\reify\lib\runtime\index.js:38:38)
W20191027-09:50:04.491(-7)? (STDERR)     at server.js (src/imports/server.js:1:1)
W20191027-09:50:04.491(-7)? (STDERR)     at fileEvaluate (packages\modules-runtime.js:336:7)
W20191027-09:50:04.491(-7)? (STDERR)     at Module.require (packages\modules-runtime.js:238:14)
=> Exited with code: 1

```

**Comment by ajitgoel** [comment]
I was able to integrate Vuelidate into the application using the plugins.js file. I am sure I will be able to integrate Vuetify also in a similar fashion. This issue can be closed.
